name: fetch

on:
#   schedule:
#   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch new data
        run: |
          yarn
          yarn fetch
      - name: commit new data
        run: |
          git config --global user.name 'NativeScript-Bot'
          git config --global user.email 'oss@nativescript.org'
          git commit -am "chore(fetch): $(date)"
          git push
